### ISSUE TITLE
ApexRPC doesn't support Olympus!

### ISSUE THREAD

**Issue by AntonMacG** [Holfz/ApexRPC#5]
Please add some assets for Olympus too!

**Comment by Holfz** [comment]
Hello @AntonMacG, 

Does the execute itself output something in logs ?

**Comment by AntonMacG** [comment]
Nope sadly not. It just says 'Playing Unknown Map' on discord

**Comment by Holfz** [comment]
Since, I am leaving this repository and issues look like dead project.

Just to clarify, I have some work and also a school project that I should get it done in a week (I also didn't play Apex since 8 Apr due to this lack of work).

Sorry, I will look at this and update it ASAP
![image](https://user-images.githubusercontent.com/32639831/164516437-35d84938-4ae0-44b7-bdb6-39d27727519b.png)

**Comment by Holfz** [comment]
Version [v1.0.2](https://github.com/Holfz/ApexRPC/releases/tag/v1.0.2) of ApexRPC was released.

Also implemented auto parsing for any unused word for termination in level value to self-fixing unknown map in the well-known existing map problem.
